# Generated by Django 5.1.1 on 2024-09-09 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pasword', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('NoSiri', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
                ('Nama', models.CharField(max_length=255)),
                ('NoKP', models.CharField(max_length=12)),
                ('Jawatan', models.CharField(blank=True, max_length=255, null=True)),
                ('TarikhKeluar', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('KadKuasa', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarikh', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('NoSiri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eKadKuasa.officer')),
            ],
        ),
    ]
